=== takumi1001/svoml/schema/svoml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="svoml" type="SvomlType" />
    <xsd:complexType name="SvomlType">
        <xsd:sequence>
            <xsd:element name="header" type="xsd:string" />
            <xsd:element name="body" type="BodyType" />
            <xsd:element name="footer" type="xsd:string" />
            <xsd:element name="arrows" type="ArrowsType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="BodyType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="g" type="GroupType" />
            <xsd:element name="h" type="GroupType" />
            <xsd:element name="s" type="GroupType" />
            <xsd:element name="v" type="GroupType" />
            <xsd:element name="o" type="GroupType" />
            <xsd:element name="c" type="GroupType" />
            <xsd:element name="t" type="xsd:string" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="GroupType" mixed="true">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="g" type="GroupType" />
            <xsd:element name="h" type="GroupType" />
            <xsd:element name="s" type="GroupType" />
            <xsd:element name="v" type="GroupType" />
            <xsd:element name="o" type="GroupType" />
            <xsd:element name="c" type="GroupType" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="ArrowsType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="di" type="ArrowType" />
            <xsd:element name="bi" type="ArrowType" />
            <xsd:element name="un" type="ArrowType" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="ArrowType">
        <xsd:attribute name="start" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="end" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== takumi1001/svoml/sample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xslt/svoml.xsl" type="text/xsl" ?>

<svoml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema/svoml.xsd">
    <header>
        SVOML Sample file 2
    </header>

    <body>
        <t>SVOML is composed from XML Schema and XLS (xml stylesheet). </t>
        <t>You can see raw SVOML file from "View Source" functions.</t>
        
        <h>
        <g>Words groups are <g>
            <g>
                <g>
                    <g>nestable</g>
                </g>
            </g>
       </g>and</g>  <s>SVOC groups</s> <v>are</v>  <c>available</c>.</h>

        <t>Also, SVOML supoorts drawing arrows from a group to a group.</t>
        <h>Directed: <g id="sdi">Start</g> <g id="edi">End</g></h>
        <h>Bidirected: <g id="sbi">Start</g> <g id="ebi">End</g></h>
        <h>Undirected <g id="sun">Start</g> <g id="eun">End</g></h>
        
        <t>
        For security issues, browsers disabled XLST if the XML file is on your local storage.
        So, you have to open SVOML files via HTTP.
        </t>
        <h>You can use localhost, for example, <g>python -m http.server </g></h>
    </body>

    <footer>
        This is a footer.
    </footer>

    <arrows>
        <di start="sdi" end="edi"></di>
        <bi start="sbi" end="ebi"></bi>
        <un start="sun" end="eun"></un>
    </arrows>
</svoml>

=== takumi1001/svoml/sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xslt/svoml.xsl" type="text/xsl" ?>

<svoml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema/svoml.xsd">
    <header>
        SVOML Sample file 1
    </header>

    <body>
        <h>Three Laws of Robotics</h>
        <t>ロボット工学3原則</t>

        <h> 1. <g><s id="robot1">A robot</s> may not <v>injure</v> <o>a human being</o> or,</g> <g>through
            inaction, <v id="allow">allow</v> <o>a human being</o> <c>to come to harm.</c></g></h>

        <t>1. ロボットは人間を傷つけてはいけない，また，傍観することによって，人間を傷つけてはいけない．</t>

        <h>2. <s>A robot</s> must <v>obey</v> <o id="orders">the orders</o> 
        <g id="given">given it by human
            beings</g> <g>except where <s>such orders</s> would <v>conflict</v> with the First Law.</g></h>

        <t>2. ロボットは，その命令が第1条に反しない限り，人間の命令に従わなければならない．</t>

        <h>3. <s>A robot</s> must <v>protect</v> <o>its own existence</o>
         <g>as long as <s>such
            protection</s> does not <v>conflict</v> with the First or Second Law.</g></h>

        <t>3. ロボットは，第1条または第2条に反しない限り，自身の存在を守らなくてはいけない．</t>
    </body>

    <footer>
        Quoted from "I, Robot." by Isaac Asimov.
    </footer>

    <arrows>
        <di start="robot1" end="allow"></di>
        <di start="given" end="orders"></di>
    </arrows>
</svoml>
